### ISSUE TITLE
cant add DDWRT router to config

### ISSUE THREAD

**Issue by jouster1974** [eelcohn/home-assistant-ddwrt#12]
added to customcomponent
gone to integration and found component
entered all details
neither have worked, always just shows unknown error occurred
have tried using hostname, IP address
used multiple combinations of SSL and Certificate option

I can access fully from browser so know it is working fine

Any ideas

**Comment by engi** [comment]
same problem with mine ...

**Comment by eelcohn** [comment]
Do you still have this problem?

**Comment by Daandeve** [comment]
I still have this problem it reports 'Unknown error occurred', so nothing useful...

**Comment by eelcohn** [comment]
Please try the following:
1. Remove any existing DD-WRT integrations from your Home Assistant setup
2. Add the following to your `configuration.yaml`:
```
logger:
  default: warning
  logs:
    custom_components.ddwrt: debug
    custom_components.ddwrt.camera: debug
    custom_components.ddwrt.config_flow: debug
    custom_components.ddwrt.binary_sensor: debug
    custom_components.ddwrt.device_tracker: debug
    custom_components.ddwrt.sensor: debug
    custom_components.ddwrt.pyddwrt: debug
```
3. Restart Home Assistant
4. Add the DD-WRT integration from the GUI
5. If you still get the error, please post the contents of the `home-assistant.log` below. **REMEMBER TO REMOVE ANY USERNAME/PASSWORDS FROM YOUR LOGFILE BEFORE YOU POST YOUR LOGFILE!**
6. Optional: remove the `logger` stuff you added in step 2 to prevent your logfile from filling up with debug info
