### ISSUE TITLE
Not able to configure it with configuration.yaml

### ISSUE THREAD

**Issue by PhilippRaab** [eelcohn/home-assistant-ddwrt#4]
When I add the config for ddwrt in the configuration.yaml the configuration does not pass the check with following error message: 
```
Invalid config for [ddwrt]: [devices] is an invalid option for [ddwrt]. Check: ddwrt->ddwrt->0->devices. (See /config/configuration.yaml, line 62)
```

My config:
```
ddwrt:
  devices:
    - name: Wifi-EG
      host: x.x.x.x
      username: admin
      password: secure_password
      ssl: false
      ....
```

**Comment by eelcohn** [comment]
Ah yes, I forgot to update the documentation. You can now setup the integration like this:
```
ddwrt:
  - host: !secret ddwrt_hostname
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    ssl: true
    verify_ssl: false
    resources:
      - clk_freq
      - cpu_temp
      - ddns_status
      - dhcp_clients
      - sw_build
      - sw_date
      - sw_version
      - ip_connections
      - lan_dhcp_start
      - lan_dhcp_end
      - lan_dhcp_lease_time
      - ....
```
